### ISSUE TITLE
Skins option still shows

### ISSUE THREAD

**Issue by girls-whocode** [barisusakli/nodebb-theme-peace#4]
I created a post on NodeBB's community group, with images. I will recap here.

I actually did find something "out of scope" for the Peace Template. I have disabled allowing members and guests to change skins. Although the little paint brush is still there, and registered users are able to change the skin.

[https://community.nodebb.org/topic/6556/nodebb-theme-peace-peace-theme-for-nodebb/11](https://community.nodebb.org/topic/6556/nodebb-theme-peace-peace-theme-for-nodebb/11)

**Comment by girls-whocode** [comment]
Currently to make it go away, I just added this to the Custom CSS/SCSS panel in the Admin:

[component="skinSwitcher"] {
  display: none !important;
}

**Comment by barisusakli** [comment]
https://github.com/barisusakli/nodebb-theme-peace/commit/ca4e3aa5e9297dbca085f39ed332f33fdf8dd37d

**Comment by girls-whocode** [comment]
Thank you, that resolved this issue.
